# Generated by Django 4.0.4 on 2022-04-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='crate_date',
            new_name='create_date',
        ),
    ]
