# Generated by Django 4.0.4 on 2022-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
